# Generated by Django 5.2.6 on 2025-09-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='session',
        ),
    ]
