# Generated by Django 5.2.6 on 2025-09-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_job_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date',
            new_name='datetime',
        ),
    ]
