# Generated by Django 5.2.6 on 2025-10-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sessionlink'),
        ),
    ]
